name: Automated tests
on: [pull_request, workflow_run]
jobs:
  includes-excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./action.yml
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            aaa/**
            **/*.foo
          excludes: |
            zzz/**

  includes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./action.yml
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            zzz/**

  excludes-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./action.yml
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          excludes: |
            zzz/**

  output-is-relevant-results:
    runs-on: ubuntu-latest
    needs:
      [
        includes-excludes-is-relevant-yes,
        includes-is-relevant-yes,
        excludes-relevant-yes,
      ]
    steps:
      - run: |
          echo 'includes & excludes is relevant yes:'
          echo ${{ needs.includes-excludes-is-relevant-yes.relevant }}
          echo 'includes is relevant yes:'
          echo ${{ needs.includes-is-relevant-yes.relevant }}
          echo 'excludes is relevant yes:'
          echo ${{ needs.excludes-is-relevant-yes.relevant }}
