name: Automated tests
on: [pull_request, workflow_dispatch]
jobs:
  includes-excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            aaa/**
            **/*.foo
          excludes: |
            zzz/**
      - name: Validate relevant output
        run: |
          if [ "${{ steps.is-relevant.outputs.relevant }}" != 'yes' ]
          then
            echo "::error::Not expected result, expected 'yes', actual '${{ steps.is-relevant.outputs.relevant }}'"
            exit 1
          fi
      - name: Validate relevant-files output
        run: |
          output_sorted=$(echo '"${{ steps.is-relevant.outputs.relevant-files }}"' | jq 'split(",") | sort_by(.) | join(",")')
          expected_sorted=$(echo '"[]"' | jq 'split(",") | sort_by(.) | join(",")')

          if [ $output_sorted != $expected_sorted ]
          then
            echo "::error::Not expected result, expected: ${expected_sorted}, actual ${output_sorted}"
            exit 1
          fi

  includes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            zzz/**
      - name: Validate response
        if: steps.is-relevant.outputs.relevant != 'yes'
        run: |
          echo "::error::Not expected result"

  excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          excludes: |
            zzz/**
      - name: Validate response
        if: steps.is-relevant.outputs.relevant != 'yes'
        run: |
          echo "::error::Not expected result"

  output-is-relevant-results:
    runs-on: ubuntu-latest
    needs:
      [
        includes-excludes-is-relevant-yes,
        includes-is-relevant-yes,
        excludes-is-relevant-yes,
      ]
    steps:
      - run: |
          echo 'using includes & excludes, expected is relevant yes: ${{ needs.includes-excludes-is-relevant-yes.outputs.relevant }}'
          echo 'only using includes, expected is relevant yes: ${{ needs.includes-is-relevant-yes.outputs.relevant }}'
          echo 'only using excludes, expected is relevant yes: ${{ needs.excludes-is-relevant-yes.outputs.relevant }}'
