name: Automated tests
on: [pull_request, workflow_dispatch]
jobs:
  includes-excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            aaa/**
            **/*.foo
          excludes: |
            zzz/**

  includes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          includes: |
            zzz/**

  excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "aaa/bbb/ccc,aaa/xxx.foo,zzz/xxx.foo"
          excludes: |
            zzz/**

  output-is-relevant-results:
    runs-on: ubuntu-latest
    needs:
      [
        includes-excludes-is-relevant-yes,
        includes-is-relevant-yes,
        excludes-is-relevant-yes,
      ]
    steps:
      - run: |
          echo 'using includes & excludes, expected is relevant yes: ${{ needs.includes-excludes-is-relevant-yes.outputs.relevant }}'
          echo 'only using includes, expected is relevant yes: ${{ needs.includes-is-relevant-yes.outputs.relevant }}'
          echo 'only using excludes, expected is relevant yes: ${{ needs.excludes-is-relevant-yes.outputs.relevant }}'
